version: '3'

services:
  backend:
    build: 
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SESSION_KEY=${SESSION_KEY}
      - PORT=8080
      - MONGODB_URL=${MONGODB_URL}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - mongodb
      - drupal
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
    networks:
      - my-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

  drupal:
    build:
      context: ./my_drupal_site
    container_name: drupal
    ports:
      - "8888:8888"
    networks:
      - my-network

networks:
  my-network:

volumes:
  mongo-data:
